- id: '1610651900649'
  alias: Turn off the lights when I leave home
  description: ''
  trigger:
  - entity_id: person.nic_durish
    event: leave
    platform: zone
    zone: zone.home
  condition: []
  action:
  - device_id: b43ca727f6fa4b4c86a6ec1cfd75c645
    domain: light
    entity_id: light.office_lamp
    type: turn_off
  - device_id: 3d66edf211f24c6eb3e0592615e4a883
    domain: light
    entity_id: light.office_light
    type: turn_off
  - device_id: 0fa69d0da9e74a7b954f517f6d48d6a3
    domain: light
    entity_id: light.desk_backlight
    type: turn_off
- id: '1610652596764'
  alias: Turn off the lights when I leave home
  description: ''
  trigger:
  - entity_id: person.nic_durish
    event: leave
    platform: zone
    zone: zone.home
  condition: []
  action:
  - device_id: b43ca727f6fa4b4c86a6ec1cfd75c645
    domain: light
    entity_id: light.office_lamp
    type: turn_off
  - device_id: 3d66edf211f24c6eb3e0592615e4a883
    domain: light
    entity_id: light.office_light
    type: turn_off
  - device_id: 0fa69d0da9e74a7b954f517f6d48d6a3
    domain: light
    entity_id: light.desk_backlight
    type: turn_off
- id: '1610652782555'
  alias: Turn off the lights when I leave home
  description: ''
  trigger:
  - entity_id: person.nic_durish
    event: leave
    platform: zone
    zone: zone.home
  condition: []
  action:
  - device_id: b43ca727f6fa4b4c86a6ec1cfd75c645
    domain: light
    entity_id: light.office_lamp
    type: turn_off
  - device_id: 3d66edf211f24c6eb3e0592615e4a883
    domain: light
    entity_id: light.office_light
    type: turn_off
  - device_id: 0fa69d0da9e74a7b954f517f6d48d6a3
    domain: light
    entity_id: light.desk_backlight
    type: turn_off
- id: '1610653037912'
  alias: Turn off the lights when I leave home
  description: ''
  trigger:
  - entity_id: person.nic_durish
    event: leave
    platform: zone
    zone: zone.home
  condition: []
  action:
  - device_id: b43ca727f6fa4b4c86a6ec1cfd75c645
    domain: light
    entity_id: light.office_lamp
    type: turn_off
  - device_id: 3d66edf211f24c6eb3e0592615e4a883
    domain: light
    entity_id: light.office_light
    type: turn_off
  - device_id: 0fa69d0da9e74a7b954f517f6d48d6a3
    domain: light
    entity_id: light.desk_backlight
    type: turn_off
