#################################
# filename: configuration.yaml
# author: Nic Durish
# created: August 2019
# updated: January 2021
#################################

default_config:

homeassistant:
  # name: Lawrence
  # latitude: !secret latitude
  # longitude: !secret longitude
  # unit_system: metric
  customize: !include customize.yaml

browser_mod:

# COMPONENTS
##############
tts:
  - platform: google_translate
    service_name: google_say

speedtestdotnet:
  scan_interval:
    minutes: 5

device_tracker:
  - platform: hitron_coda
    host: 192.168.0.1
    username: !secret wifi_user
    password: !secret wifi_pass
    type: rogers

google:
  client_id: !secret google_cal_id
  client_secret: !secret google_cal_secret

ecobee:
  api_key: !secret ecobee_key

hue:
  bridges:
    - host: 192.168.0.14

spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

tplink:
  discovery: true
  switch:
    - host: 192.168.0.20
    - host: 192.168.0.21

ecobee:
  api_key: !secret ecobee_key

# INCLUDES
####################
sensor: !include includes/sensors.yaml
script: !include includes/scripts.yaml
# group: !include includes/groups.yaml
automation: !include includes/automations.yaml
scene: !include includes/scenes.yaml
light: !include includes/light-groups.yaml


# INPUTS AND BAYESION SENSORS
####################
input_select:
  house_status:
    name: House Status
    icon: mdi:home
    options:
      - Home
      - Asleep
      - Away
      - Vacation

input_boolean:
  guest_mode:
    name: Guest Mode
    icon: mdi:account-plus
    initial: off

# USER INTERFACE
###########
lovelace:
  mode: storage

frontend:
  extra_module_url:
    - /hacsfiles/custom-sidebar/custom-sidebar.js
  themes: !include_dir_merge_named themes
#map:

logbook:
  # exclude:
  #   domains:
  #     - sensor

  # include:
  #   entities:
  #   - sensor.house_status
  #   - sensor.nic_status
  #   - sensor.emma_status
  #   - sensor.guest_status
  #
  #   - binary_sensor.bedroom_occupancy
  #   - binary_sensor.office_occupancy
  #
  #   - light.exterior
  #   - light.living_room
  #   - light.bedroom
  #   - light.office
  #   domains:
  #     - devices
  #     - script

history:
  use_include_order: True
  include:
    entities:
      - sensor.house_status
      - sensor.guest_status

      - person.nic_durish
      - person.emma_henry

      - sensor.ups_battery_charge
      - sensor.ups_load
      - sensor.ups_status

      - sensor.living_room_temperature
      - sensor.living_room_humidity
      - sensor.bedroom_temperature
      - sensor.sensor2_temperature
      - climate.living_room
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.plex_durnydrive
      - weather.lawrence
      - sensor.weather_temperature
    domains:
      - light
      - switch
      - device
  exclude:
    entities:
      - light.exterior
      - light.office
      - light.bedroom_1
      - light.bedroom_2
      - light.living_room

config:

recorder:
  purge_keep_days: 365
