#################################
# filename: configuration.yaml
# author: Nic Durish
# created: August 2019
# updated: January 2021
#################################

homeassistant:
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config/.storage

default_config:

# COMPONENTS
##############
# tts:
#   - platform: google_translate
#     service_name: google_say

speedtestdotnet:
  scan_interval:
    minutes: 5

device_tracker:
  - platform: hitron_coda
    host: http://192.168.0.1
    username: !secret wifi_user
    password: !secret wifi_pass
    type: rogers

google:
  client_id: !secret google_cal_id
  client_secret: !secret google_cal_secret

ecobee:
  api_key: !secret ecobee_key

hue:
  bridges:
    - host: 192.168.0.14

spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

tplink:
  discovery: true
  switch:
    - host: 192.168.0.20
    - host: 192.168.0.21

# INCLUDES
####################
sensor: !include includes/sensors.yaml
script: !include includes/scripts.yaml
automation manual: !include_dir_merge_list includes/automations/
scene manual: !include includes/scenes.yaml
light: !include includes/light-groups.yaml

# Managed via UI
####################
scene ui: !include scenes.yaml
automation ui: !include automations.yaml

# INPUTS AND BAYESION SENSORS
####################
input_select:
  house_status:
    name: House Status
    icon: mdi:home
    options:
      - Home
      - Asleep
      - Away
      - Vacation

input_boolean:
  guest_mode:
    name: Guest Mode
    icon: mdi:account-plus
    initial: off

shell_command:
  convert_lovelace: python /config/utils/json2yaml.py /config/.storage/lovelace /config/lovelace-ui.yaml


folder_watcher:
  - folder: /config/.storage

# USER INTERFACE
###########
lovelace:
  mode: storage

frontend:
  extra_module_url:
    - /hacsfiles/custom-sidebar/custom-sidebar.js
  themes: !include_dir_merge_named themes

history:
  use_include_order: True
  include:
    entities:
      - sensor.house_status
      - sensor.guest_status

      - person.nic_durish
      - person.emma_henry

      - sensor.ups_battery_charge
      - sensor.ups_load
      - sensor.ups_status

      - sensor.living_room_temperature
      - sensor.living_room_humidity
      - sensor.bedroom_temperature
      - sensor.sensor2_temperature
      - climate.living_room
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.plex_durnydrive
      - weather.lawrence
      - sensor.weather_temperature
    domains:
      - light
      - switch
      - device
  exclude:
    entities:
      - light.exterior
      - light.office
      - light.bedroom_1
      - light.bedroom_2
      - light.living_room

config:

recorder:
  purge_keep_days: 365
