title: Control Panel
custom_header:
  compact_mode: true
  button_text:
      options: '{{ hours12 }}:{{ minutesLZ }}'

views:

# Mainview
#############
  - title: Home
    icon: mdi:home
    badges:
      - person.nic_durish
      - person.emma_henry
      - person.mike_hager



    cards:


      - type: custom:auto-entities
        show_empty: true
        card:
          type: glance
          show_header_toggle: false
        filter:
          include:
            - entity_id: "person.nic_durish"


      - type: custom:vertical-stack-in-card
        cards:
          - type: glance
            show_name: false
            entities:
              - sensor.house_status
              - sensor.living_room_humidity
              - sensor.light_on_count
              - sensor.switch_on_count
          - type: custom:simple-thermostat
            entity: climate.living_room
            #step_layout: row
            # name: false
            # icon: false
            # control: false

      - type: thermostat
        entity: climate.living_room

    #SCENES
      - type: glance
        title: "Scenes"
        show_state: false
        entities:
          - entity: script.alloff_scene
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.alloff_scene
          - entity: script.concentrate_scene
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.concentrate_scene
          - entity: script.bright_scene
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.bright_scene
          - entity: script.warm_scene
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.warm_scene
          - entity: script.relax_scene
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.relax_scene
          - entity: script.dimmed_scene
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.dimmed_scene
          - entity: script.bed_scene
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.bed_scene



      - type: weather-forecast
        entity: weather.lawrence


      - title: Living Room
        type: entities
        entities:
          - light.hall_light
          - light.living_room_light
          - light.entrance_light
          - light.lamp
          - remote.50_sharp_roku_tv
          - switch.saltlamp
          - switch.stringlight
          - sensor.living_room_temperature

      - title: Living Room
        type: entities
        entities:
          - type: custom:slider-entity-row
            entity: light.entrance_light
            secondary_info: last-changed
            toggle: true
          - type: custom:slider-entity-row
            entity: light.living_room_light
            secondary_info: last-changed
            toggle: true
          - type: custom:slider-entity-row
            entity: light.hall_light
            secondary_info: last-changed
            toggle: true
          - entity: switch.stringlight
            secondary_info: last-changed
          - entity: switch.floorlamp
            secondary_info: last-changed
          - entity: media_player.living_room
            type: custom:mini-media-player
            name: Roku
            show_source: true
            artwork: cover
            power_color: false
            hide_volume: false
            scroll_info: true
            group: true
          - entity: media_player.livingroom_tv
            type: custom:mini-media-player
            name: Chromecast Ultra
            show_source: true
            artwork: cover
            power_color: false
            hide_volume: false
            scroll_info: true
            group: true
          - entity: media_player.livingroom_speaker
            type: custom:mini-media-player
            name: Google Home Mini
            show_source: true
            artwork: cover
            power_color: false
            hide_volume: false
            scroll_info: true
            group: true

      - title: Bedroom
        type: entities
        entities:
          - group.bedroom_lights
          - light.bedroom_2
          - light.nics_light
          - light.bedroom_1
          - light.emmas_light
          - sensor.bedroom_temperature

      - title: Kitchen
        type: entities
        entities:
          - entity: light.kitchen_light

      - title: Exterior
        type: entities
        entities:
          #- light.coop
          - light.porch_light
          - switch.plug_4

      - title: Office
        type: entities
        entities:
          - light.office_lamp
          - light.office_light
          - light.desk_backlight
          - sensor.canon_mx530_series_black
          - sensor.canon_mx530_series_color
          - sensor.canon_mx530_series
          - switch.plug_3


      - title: Upstairs
        type: entities
        entities:
          - light.guest_bedroom_1
          - light.guest_bedroom_2
          - sensor.sensor2_temperature



# Systems
#############
  - title: Systems
    icon: mdi:server
    badges:
      - entity: sensor.speedtest_ping
      - entity: sensor.speedtest_download
      - entity: sensor.speedtest_upload

    cards:
      - type: entities
        entities:
          - sensor.bedroom_dimswitch_battery_level
          - sensor.livingroom_dimswitch_battery_level
          - sensor.office_dimswitch_battery_level

      - title: ServerRack
        type: entities
        entities:
          - sensor.synology_cpu_load_total
          - sensor.synology_memory_usage_real
          - sensor.synology_memory_total_real
          - sensor.synology_network_up
          - sensor.synology_network_down
          - sensor.synology_status_volume_1
          - sensor.synology_total_size_volume_1
          - sensor.synology_used_space_volume_1
          - sensor.synology_average_disk_temp_volume_1
          - sensor.plex_durnydrive
          - sensor.hacs



      - type: media-control
        entity: media_player.all

# Settings
#############
  - title: Settings
    icon: mdi:settings
    cards:
      - type: entities
        entities:
          - input_boolean.guest_mode
        title: Input boolean
      - type: entities
        entities:
          - input_select.house_status
        title: Input select

# Junk
#############
  - title: junk
    icon: mdi:delete

    cards:
      - type: media-control
        entity: media_player.bathroom_speaker
      - type: media-control
        entity: media_player.bedroom_speaker
      - type: media-control
        entity: media_player.kitchen_speaker
      - type: media-control
        entity: media_player.livingroom_tv
      - type: media-control
        entity: media_player.50_sharp_roku_tv
      - type: entities
        entities:
          - calendar.family
        title: Calendar
