###########
#RESOURCES
###########
resources:
  - url: /customcards/mini-media-player-bundle.js
    type: module
  - url: /customcards/vertical-stack-in-card.js
    type: js
  - url: /customcards/slider-entity-row.js
    type: module
  - url: /customcards/card-modder.js
    type: module
  - url: /customcards/card-tools.js
    type: js
  - url: /customcards/layout-card.js
    type: js
  - url: /customcards/compact-custom-header.js
    type: module
  - url: /customcards/group-card.js
    type: js
  - url: https://unpkg.com/moment@2.22.2/moment.js
    type: js
  - url: /customcards/calendar-card.js
    type: module
  - url: /customcards/fold-entity-row.js
    type: js 
  - url: /customcards/button-card.js
    type: js 
  - url: /customcards/atomic-calendar.js
    type: module
  - url: /customcards/github/custom-cards/tracker-card.js?track=true
    type: module
  - url: /local/surveillance-card.js
    type: module
  - url: /local/spotify-card.js
    type: module
  - url: /local/markdown-mod.js
    type: module
  - url: /local/monster-card.js
    type: js
  - url: /local/auto-entities.js
    type: js
  - url: /local/card-mod.js
    type: module


cch:
  disable: false
  header: true
  menu: show
  sidebar_swipe: true
  notifications: show
  voice: hide
  options: clock
  clock_format: 24
  clock_date: true
  swipe: true
  exceptions:
    - conditions:
        user: kiosk
      config:
        show_tabs: 10
        kiosk_mode: true
        
#decluttering_templates:

title: "Home"

views:
  - !include lovelace/000_floorplan.yaml
  - !include lovelace/010_overview.yaml
  - !include lovelace/020_cams.yaml
  - !include lovelace/030_systems.yaml
  - !include lovelace/040_settings.yaml
