- alias: "Convert Lovelace configuration to yaml"
  trigger:
    platform: event
    event_type: folder_watcher
    event_data:
      event_type: modified
  action:
    service: shell_command.llconvert

- alias: "OFFICE_DIMSWITCH - Fireplace Toggle"
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.office_dimswitch
      to: '1_hold'
    - platform: state
      entity_id: sensor.office_dimswitch
      to: '4_hold'
  action:
    - service: switch.toggle
      entity_id: switch.plug_3

- alias: "OFFICE_DIMSWITCH - Fireplace Off"
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.office_dimswitch
      to: '4_click'
    - platform: state
      entity_id: sensor.office_dimswitch
      to: '4_click_up'
  action:
    - service: switch.turn_off
      entity_id: switch.plug_3

- alias: "OFFICE_DIMSWITCH - Fireplace On"
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.office_dimswitch
      to: '1_click'
    - platform: state
      entity_id: sensor.office_dimswitch
      to: '1_click_up'
  action:
    - service: switch.turn_on
      entity_id: switch.plug_3

- alias: "BEDROOM_DIMSWITCH - Nightlight"
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.bedroom_dimswitch
      to: '4_hold'
  action:
    - service: light.turn_on
      data:
        entity_id: light.nics_light
        brightness: 50

- alias: "LR_DIMSWITCH - Toggle Switches"
  initial_state: true
  trigger:
    - platform: state
      entity_id: sensor.livingroom_dimswitch
      to: '1_hold'
    - platform: state
      entity_id: sensor.livingroom_dimswitch
      to: '4_hold'
  action:
    - service: switch.toggle
      entity_id: switch.floorlamp
    - service: switch.toggle
      entity_id: switch.stringlight
    - service: switch.toggle
      entity_id: switch.plug_4

- alias: "GUESTS - Set Home when guest"
  trigger:
    platform: state
    entity_id: input_boolean.guest_mode
    to: 'on'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: input_select.house_status
      state: "Away"
    - condition: state
      entity_id: input_select.house_status
      state: "Vacation"
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.house_status
      option: "Home"

#######################
# HOUSE STATE CHANGES #
#######################
- alias: "HSTATE - Mode Coming Home"
  trigger:
    - platform: state
      entity_id: binary_sensor.nic_presence, binary_sensor.emma_presence
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: input_select.nic_status
      to: 'Just Arrived'
    - platform: state
      entity_id: input_select.emma_status
      to: 'Just Arrived'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: input_select.house_status
      state: "Away"
    - condition: state
      entity_id: input_select.house_status
      state: "Vacation"
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.house_status
      option: "Home"

- alias: "HSTATE - Mode Going Away"
  trigger:
    - platform: state
      entity_id: input_select.nic_status
      to: 'Away'
    - platform: state
      entity_id: input_select.emma_status
      to: 'Away'
  condition:
    condition: and
    conditions:
    - condition: or
      conditions:
      - condition: state
        entity_id: input_select.nic_status
        state: 'Away'
      - condition: state
        entity_id: input_select.nic_status
        state: 'Extended Away'
    - condition: or
      conditions:
      - condition: state
        entity_id: input_select.emma_status
        state: 'Away'
      - condition: state
        entity_id: input_select.emma_status
        state: 'Extended Away'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.house_status
      option: "Away"

- alias: "HSTATE - Mode Going On Vacation"
  trigger:
    - platform: state
      entity_id: input_select.nic_status
      to: 'Extended Away'
    - platform: state
      entity_id: input_select.emma_status
      to: 'Extended Away'
  condition:
    - condition: state
      entity_id: input_select.nic_status
      state: 'Extended Away'
    - condition: state
      entity_id: input_select.emma_status
      state: 'Extended Away'
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.house_status
      option: "Vacation"
