- platform: yr
  name: Weather
  forecast: 24
  monitored_conditions:
    - temperature

# SIMPLIFIERS
###############
- platform: template
  sensors:
    climate_combined:
      value_template: "{{ state_attr('climate.living_room', 'target_temp_low') }}/{{ state_attr('climate.living_room', 'target_temp_high') }}"
      entity_id: climate.living_room
    house_status:
      value_template: '{{ states.input_select.house_status.state }}'
      friendly_name: 'House Status'
    guest_status:
      value_template: '{{ states.input_boolean.guest_mode.state }}'
      friendly_name: 'Guest Mode'
    # local_time:
    #   value_template: "{{as_timestamp(now()) | timestamp_custom('%-I:%M %p')}}"
    #   entity_id: sensor.time
    # local_date:
    #   value_template: "{{as_timestamp(now()) | timestamp_custom('%A %B %-d')}}"
    #   entity_id: sensor.date



- platform: template
  sensors:
    script_count:
      value_template: "{{ states | selectattr('entity_id','in',state_attr('group.all_scripts','entity_id')) | list | count }}"
      friendly_name: 'Scripts'
    automation_count:
      value_template: "{{ states | selectattr('entity_id','in',state_attr('group.all_automations','entity_id')) | list | count }}"
      friendly_name: 'Automations'
    light_count:
      value_template: "{{ states | selectattr('entity_id','in',state_attr('group.all_lights','entity_id')) | list | count }}"
      friendly_name: 'Lights'
    light_on_count:
      entity_id: sensor.time
      value_template: "{{ states['light'] | selectattr('state','eq', 'on') | list | count }}"
    switch_count:
      value_template: "{{ states | selectattr('entity_id','in',state_attr('group.all_switches','entity_id')) | list | count }}"
      friendly_name: 'Switches'
      unit_of_measurement: "min"
    switch_on_count:
      entity_id: sensor.time
      value_template: "{{ states['switch'] | selectattr('state','eq', 'on') | list | count }}"


#################
# REST COMMANDS #
#################
# - platform: rest
#   resource: https://pypi.python.org/pypi/homeassistant/json
#   name: HA upstream
#   value_template: '{{ value_json.info.version }}'
#   scan_interval: 3600
